### ISSUE TITLE
Change prefix URI syntax in the query from . to : 

### ISSUE THREAD

**Issue by deiu** [dan-f/twinql#25]
Currently, the query uses a `prefix.property` syntax. This is not very useful since the response format is JSON-LD and keys use the `prefix:property` syntax.

**Comment by dan-f** [comment]
This change will probably affect the lexer here:

https://github.com/dan-f/twinql/blob/master/src/lang/lexer.js#L172-L184

and the token regexes here:

https://github.com/dan-f/twinql/blob/master/src/lang/tokens.js#L35-L39
