### ISSUE TITLE
Twinql is Undefined for Query from the Browser when running in FireFox

### ISSUE THREAD

**Issue by bshambaugh** [dan-f/twinql#32]
Error: twinql is undefined for "query from the browser button" lines 71-74 in app.js:
const onTheClient = queryText => {
  const backend = new twinql.WebBackend({ proxyUri: 'https://databox.me/,proxy?uri=' })
  return twinql.query(backend, queryText)
}

**Comment by bshambaugh** [comment]
CLI output when running:

[Thu Apr 20 2017 20:46:57 GMT-0500 (CDT)] "GET /" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0"
[Thu Apr 20 2017 20:46:57 GMT-0500 (CDT)] "GET /public/app.js" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0"
[Thu Apr 20 2017 20:46:57 GMT-0500 (CDT)] "GET /build/bundle.js" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0"
[Thu Apr 20 2017 20:46:57 GMT-0500 (CDT)] "GET /build/bundle.js" Error (404): "Not found"
[Thu Apr 20 2017 20:46:57 GMT-0500 (CDT)] "GET /public/style.css" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0"
[Thu Apr 20 2017 20:46:58 GMT-0500 (CDT)] "GET /public/GitHub-Mark-120px-plus.png" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0"
[Thu Apr 20 2017 20:46:59 GMT-0500 (CDT)] "GET /build/bundle.js" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0"
[Thu Apr 20 2017 20:46:59 GMT-0500 (CDT)] "GET /build/bundle.js" Error (404): "Not found"
[Thu Apr 20 2017 20:47:00 GMT-0500 (CDT)] "GET /public/favicon.ico" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0"
[Thu Apr 20 2017 20:52:12 GMT-0500 (CDT)] "GET /" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0"
[Thu Apr 20 2017 20:52:12 GMT-0500 (CDT)] "GET /public/app.js" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0"
[Thu Apr 20 2017 20:52:12 GMT-0500 (CDT)] "GET /build/bundle.js" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0"
[Thu Apr 20 2017 20:52:12 GMT-0500 (CDT)] "GET /public/style.css" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0"
[Thu Apr 20 2017 20:52:12 GMT-0500 (CDT)] "GET /build/bundle.js" Error (404): "Not found"
[Thu Apr 20 2017 20:52:12 GMT-0500 (CDT)] "GET /build/bundle.js" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0"
[Thu Apr 20 2017 20:52:12 GMT-0500 (CDT)] "GET /build/bundle.js" Error (404): "Not found"
[Thu Apr 20 2017 20:52:13 GMT-0500 (CDT)] "GET /public/GitHub-Mark-120px-plus.png" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0"
^Chttp-server stopped.

**Comment by bshambaugh** [comment]
In Chrome:

bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:72 Uncaught ReferenceError: twinql is not defined
    at onTheClient (app.js:72)
    at runQuery (app.js:103)
    at HTMLButtonElement.document.querySelector.addEventListener (app.js:95)

**Comment by bshambaugh** [comment]
This happens with the demo site (stopping at step 3). This may not be a bug since WebPack creates bundle.js. Solved. Do:  `npm run build:umd` in step 4 with WebPack before trying `npm start` in step 3.

**Comment by dan-f** [comment]
Hey @bshambaugh. Thanks for testing things out! Sounds like you figured this one out yourself. If you're running locally, you have to build the bundle before starting the server.
